[tool.poetry]
name = "committee-scripts"
version = "0.1.0"
description = ""
authors = ["kate-aleksseeva <kate_aleksseeva@lido.fi>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
